apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ci-cd-project
  labels:
    app: java
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: java
  template: 
    metadata: 
      labels: 
        app: java
    spec:
      containers:
      - name: tomcat
        image: mohammed2asif/ci-cd-project
        ports: 
        - containerPort: 80


apiVersion: v1
kind: Service
metadata: 
  name: ci-cd-project-service
spec: 
  type: LoadBalancer
  ports: 
  - port: 80
  selector: 
    app: tomcat
